Module5 task2
htmlacademy-react/802987-six-cities-5 pull request #10
Opened 2020-11-03 12:19 UTC by neeptoon

2020-11-04 14:35 UTC, IArny requested changes

2020-11-04 14:35 UTC, IArny commented on src/components/card-list/card-list.jsx
> +        activeCard: offers.find((offer) => offer.id.toString() === currentID).id
для чего тебе нужен activeCard в стейте компонента?

2020-11-04 14:35 UTC, IArny commented on src/store/action.js
> +  GET_ACTIVE_CARD: `GET_ACTIVE_CARD`,
по логике получается, что это не GET_ACTIVE_CARD, а SET_ACTIVE_CARD имхо

2020-11-04 14:35 UTC, IArny commented on src/components/places-sort-option/sort-type.js
> +export const SortType = [{name: `DEFAULT`, value: `Popular`}, {name: `TO_HIGHT`, value: `Price: low to high`}, {name: `TO_LOW`, value: `Price: high to low`}, {name: `BY_RATE`, value: `Top rated first
разбей по строчкам плиз, а то не читается

2020-11-04 14:35 UTC, IArny commented on src/components/map/map.jsx
> +    this.offers.filter((offer) => offer.city === `Amsterdam`)
Получается дублирование кода который на 33ей строчке, лучше вынести фильртацию и отрисовку в общий метод и вызывать уже его в didMount и didUpdate

2020-11-04 15:06 UTC, neeptoon commented on src/components/card-list/card-list.jsx
> +        activeCard: offers.find((offer) => offer.id.toString() === currentID).id
http://joxi.ru/Rmz0nQbcMYovaA этого требует задание

2020-11-04 15:22 UTC, neeptoon commented on src/components/places-sort-option/sort-type.js
> +export const SortType = [{name: `DEFAULT`, value: `Popular`}, {name: `TO_HIGHT`, value: `Price: low to high`}, {name: `TO_LOW`, value: `Price: high to low`}, {name: `BY_RATE`, value: `Top rated first
поправил

2020-11-04 15:23 UTC, neeptoon commented on src/store/action.js
> +  GET_ACTIVE_CARD: `GET_ACTIVE_CARD`,
логично....

2020-11-04 15:50 UTC, neeptoon commented on src/components/map/map.jsx
> +    this.offers.filter((offer) => offer.city === `Amsterdam`)
отлично! так и сделал!

2020-11-05 07:53 UTC, IArny commented on src/components/map/map.jsx
> +  renderPinToCard() {
метод лучше по другому назвать, рендер используется для реактовских рендеров

2020-11-06 12:06 UTC, merged