Module6 task1
htmlacademy-react/802987-six-cities-5 pull request #12
Opened 2020-11-09 10:18 UTC by neeptoon

2020-11-10 18:56 UTC, IArny requested changes

2020-11-10 18:56 UTC, IArny commented on src/components/card-list/card-list.jsx
> +      {offers.map((offer, id) => <CardContainer key={id.toString()} offer={offer} handleCardOut={handleCardOut} handleCardOver={handleCardOver} path={location.pathname} match={match} />
а зачем к строке в key приводить?

2020-11-10 18:56 UTC, IArny commented on src/components/card-list/card-list.jsx
> +  setActiveCardId(activeCardId) {
Можно использовать bindActionCreators чтоб не оборачивать лишний раз в функцию
https://redux.js.org/api/bindactioncreators

2020-11-10 18:56 UTC, IArny commented on src/hocs/with-active-card-id.jsx
> +          componentDidUpdate={this.componentDidUpdate}
Это зачем?? Кажется, что-то намудрил

2020-11-11 09:04 UTC, neeptoon commented on src/components/card-list/card-list.jsx
> +      {offers.map((offer, id) => <CardContainer key={id.toString()} offer={offer} handleCardOut={handleCardOut} handleCardOver={handleCardOver} path={location.pathname} match={match} />
у какого то чувака в статье прочитал что бы исключть возможный конфликт ключей с id-шниками. Не понял правда как они могут конфликтовать но решил попробовать так сделать. Похоже это не соответствует действительности, раз ты обратил внимание.

2020-11-11 11:36 UTC, neeptoon commented on src/hocs/with-active-card-id.jsx
> +          componentDidUpdate={this.componentDidUpdate}
ну как же.... передаю обработчики в пропсах компоненту, который будет передаваться в этот HOC

2020-11-11 15:10 UTC, IArny approved these changes

2020-11-11 15:10 UTC, merged