Module3 task1
htmlacademy-react/802987-six-cities-5 pull request #6
Opened 2020-10-13 06:17 UTC by neeptoon

2020-10-13 10:31 UTC, IArny requested changes

2020-10-13 10:31 UTC, IArny commented on src/components/advantage/advantage.jsx
> +        <li key={index.toString() + new Date()} className="property__inside-item">
не очень хорошее решение с new Date, реакт будет перерисовывать элемент на каждый вызов функции

2020-10-13 10:31 UTC, IArny commented on src/components/card-list/card-list.jsx
> +      <Card key={index} id={index} offer={offer} handleCardOver={this.handleCardOver} handleCardOut={this.handleCardOut}/>
Если я не ошибаюсь, то в offer есть id, почему ты не передаешь его в качестве key и id

2020-10-13 10:31 UTC, IArny commented on src/components/card-list/card-list.jsx
> +      <Card key={index} id={index} offer={offer} handleCardOver={this.handleCardOver} handleCardOut={this.handleCardOut}/>
и для чего вообще передавать id, если ты его не используешь

2020-10-13 10:31 UTC, IArny commented on src/components/favorites-card/favorites-card.jsx
> +const FavoritesCard = ({currentOffer}) => {
разве эта карточка не совпадает с обычной card.jsx?

2020-10-13 10:31 UTC, IArny commented on src/components/image/image.jsx
> +        <div key={index.toString() + new Date()} className="property__image-wrapper">
опять же new Date

2020-10-13 10:31 UTC, IArny commented on src/components/review/review.jsx
> +        <li key={index} className="reviews__item">
могут возникнуть проблемы с сортировкой из за использования index в качестве key

2020-10-13 10:31 UTC, IArny commented on src/propTypes/propTypes.jsx
> +      user: PropTypes.string,
добавь id для коммента тоже

2020-10-13 12:20 UTC, neeptoon commented on src/components/advantage/advantage.jsx
> +        <li key={index.toString() + new Date()} className="property__inside-item">
подсмотрел на каком то канале..... убрал. Ключ должен ведь быть уникальным в пределах компонента, оставил индекс

2020-10-13 12:21 UTC, neeptoon commented on src/components/card-list/card-list.jsx
> +      <Card key={index} id={index} offer={offer} handleCardOver={this.handleCardOver} handleCardOut={this.handleCardOut}/>
тут забыл удалить id в принципе

2020-10-15 08:10 UTC, neeptoon commented on src/components/card-list/card-list.jsx
> +      <Card key={index} id={index} offer={offer} handleCardOver={this.handleCardOver} handleCardOut={this.handleCardOut}/>
а нет....этот id я использую для передачи активной карточки в стейт компонента

2020-10-15 08:28 UTC, IArny commented on src/components/card-list/card-list.jsx
> +      <Card key={index} id={index} offer={offer} handleCardOver={this.handleCardOver} handleCardOut={this.handleCardOut}/>
что значит активной? index же это текущий порядковый номер каждой карточки

2020-10-15 08:50 UTC, neeptoon commented on src/components/card-list/card-list.jsx
> +      <Card key={index} id={index} offer={offer} handleCardOver={this.handleCardOver} handleCardOut={this.handleCardOut}/>
http://joxi.ru/ZrJabjdun3X6NA
Каждой карточке я передаю коллбэки которые срабатывают при наведении курсора на карточку и записывают в стейт родительского компонента CardList активную карточку следующим образом: получив currentTarget.id ищут в массиве всех предложений одно с таким же id и передают его в стейт.

2020-10-15 14:39 UTC, IArny approved these changes

2020-10-15 14:39 UTC, merged